version: '3.4'

services:
  catologdb:
    image: mongo
 
  discount.api:
    image: ${DOCKER_REGISTRY-}discount.api
    build:
        context: .
        dockerfile : ../../run-aspnetcore-microservices/src/Services/Discount/Discount.API/Dockerfile
  
  discountdb:
      image: postgres
  pgadmin:
    image: dpage/pgadmin4
  catolog.api:
    image: ${DOCKER_REGISTRY-}catologapi
    build:
      context: .
      dockerfile: Services/Catalog/Catolog.API/Dockerfile

volumes:
   postgres_data:
   pgadmin_data:
    
