version: '3.4'

services:
  catologdb:
    container_name: catologDb
    restart: always
    ports:
      - "27014:27017"

  discount.api:
        container_name: discount.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "DatabaseSettings:ConnectionString=Server=discountdb;Host:discountdb;Port=5555;Database=discountDb;User Id=admin;Password=admin;"
          - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
          - discountdb
        ports:
          - "8002:80"
  discountdb:
    container_name: discoutndb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data
  
  pgadmin:
   container_name: pgadmin
   environment:
    - PGADMIN_DEFAULT_EMAIL=admin@aspnet.com
    - PGADMIN_DEFAULT_PASSWORD=admin
   restart: always
   ports:
     - "5050:80"
   volumes:
     - pgadmin_data:/root/.pgadmin
  catolog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting: ConnectionString: mongodb://localhost:27017"
    depends_on:
      - catologdb
    ports:
      - "8000:80"
